<link href="{{asset('site/img/favicon.ico')}}" rel="icon">
<link href="{{asset('site/img/apple-touch-icon.png')}}" rel="apple-touch-icon">
<link href="{{asset('site/vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('site/css/font-awesome.min.css')}}" rel="stylesheet">
<link href="{{asset('site/vendor/animate.css/animate.min.css')}}" rel="stylesheet">
<link href="{{asset('site/vendor/icofont/icofont.min.css')}}" rel="stylesheet">
<link href="{{asset('site/vendor/boxicons/css/boxicons.min.css')}}" rel="stylesheet">
<link href="{{asset('site/vendor/venobox/venobox.css')}}" rel="stylesheet">
<link href="{{asset('site/vendor/owl.carousel/assets/owl.carousel.min.css')}}" rel="stylesheet">
<link href="{{asset('site/vendor/aos/aos.css')}}" rel="stylesheet">
<link href="{{asset('site/css/style.css')}}" rel="stylesheet">
